services:
  backend:
    build: ./backend
    ports:
      - "8001:8000"
    volumes:
      - ./backend:/app
  frontend:
    build: ./frontend/hvac-sim
    ports:
      - "8080:3000"
    volumes:
      - ./frontend:/app
    depends_on:
    - backend
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    