services:
  backend:
    build: ./backend
    ports:
      - "8001:8000"
    volumes:
      - ./backend:/app
  frontend:
    build: ./frontend/hvac-sim
    ports:
      - "8080:3000"
    volumes:
      - ./frontend:/app
    depends_on:
    - backend
  mqtt_server:
    build: ./mqttServer
    ports: 
      - "8004:8004"
    volumes:
      - ./mqttServer:/app